import "./globals.css";
import styles from "./page.module.css";

export const metadata = {
  title: "First Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}> {children}</main>
      </body>
    </html>
  );
}
